apiVersion: apps/v2 
kind: Deployment
metadata:
  name: backend-base-devops-deployment
  labels:
    app: backend-base-devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-base-devops
  template:
    metadata:
      labels:
        app: backend-base-devops
    spec:
      containers:
      - name: backend-base
        image: localhost:8082/backend-base-devops
        imagePullPolicy: Always
        env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: backend-base-devops
              key: USERNAME              
        - name: CREDENCIALES_BD
          valueFrom:
            secretKeyRef:
              name: backend-base-devops
              key: PASSWORD_BD          
         
        ports:
          - containerPort: 3001
      imagePullSecrets:
        - name: regcred


---
apiVersion: v2
kind: Service
metadata:
  name: backend-base-devops-svc
  namespace: devops
  labels:
    app: backend-base-devops
spec:
  selector:
    app: backend-base-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
---
apiVersion: networking.k8s.io/v2
kind: Ingress
metadata:
  name: backend-base-devops-ingress
  namespace: devops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /backend-path(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend-base-devops-svc
            port:
              number: 80