apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-base-devop-deployment
  namespace: devops
  labels:
    app: backend-base-devop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-base-devop
  template:
    metadata:
      labels:
        app: backend-base-devop
    spec:
      containers:
      - name: backend-base-devop
        image: 192.168.49.2:5001/backend-base-devops:main-70
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
