apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-base-devop-deployment
  namespace: devops
  labels:
    app: backend-base-devop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-base-devop
  template:
    metadata:
      labels:
        app: backend-base-devop
    spec:
      containers:
      - name: backend-base-devop
        image: localhost:5001/backend-base-devops:main-70
        imagePullPolicy: IfNotPresent
        env:
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: backend-base-devop
              key: USER
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: backend-base-devop
              key: API_KEY
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: regcred
